### ISSUE TITLE
Compatibilità Python 3

### ISSUE THREAD

**Issue by pnicolli** [italia/design.plone.theme#64]
Sarebbe bene avere il prima possibile il codice compatibile con Python 3, per poter iniziare a lavorare sulla prossima versione 5.2 di Plone in previsione della morte di Python 2 dell'1 gennaio 2020.

Sebbene i lavori di test siano già partiti (@cekk) lascio qui questa issue come placeholder da inserire per la milestone della prossima major version del tema.

**Comment by nzambello** [comment]
Risolto in [v5.0.0](https://github.com/italia/design.plone.theme/blob/master/CHANGES.rst#500-2020-05-13)
