### ISSUE TITLE
Rendere coerente l'utilizzo delle griglie css

### ISSUE THREAD

**Issue by pnicolli** [italia/design.plone.theme#73]
Tutto il tema è basato su bootstrap, ma viene invece forzato l'uso delle griglie css per le tiles. Questa cosa crea talvolta inconsistenze nei temi derivati da questo, con padding strani e più complessi da gestire per i vari casi d'uso.

Mi riferisco a queste righe:
https://github.com/italia/design.plone.theme/blob/7082cf91c44d65ff57230f3db5993dea723b6a28/src/design/plone/theme/theme/sass/components/_tiles_base.scss#L156

Secondo me dovremmo scegliere tra:

- Basare tutto il tema su grid
- Rimuovere grid

Mi piace di più la seconda strada perché non credo abbiamo realmente bisogno delle griglie, dobbiamo solo affiancare cose e nemmeno troppo spesso. Inoltre, rimuoverle dal punto che ho linkato è più rapido rispetto ad adattare tutto il tema.

**Comment by nzambello** [comment]
rimosse grids https://github.com/italia/design.plone.theme/pull/85
