### ISSUE TITLE
Plone 5.2rc5

### ISSUE THREAD

**Issue by yurj** [italia/design.plone.theme#75]
Il tema si installa come pure collective.editablemenu, senza problemi. C'è un problema con la gestione dei tile. Questo l'errore:

2019-07-10 17:20:04,272 ERROR   [Zope.SiteErrorLog:251][waitress] 1562772004.270.219560376198 http://localhost:8080/Tema/homepage/@@add-tile
Traceback (innermost last):
  Module ZPublisher.WSGIPublisher, line 155, in transaction_pubevents
  Module ZPublisher.WSGIPublisher, line 337, in publish_module
  Module ZPublisher.WSGIPublisher, line 255, in publish
  Module ZPublisher.mapply, line 85, in mapply
  Module ZPublisher.WSGIPublisher, line 61, in call_object
  Module plone.app.tiles.browser.traversal, line 138, in __call__
  Module Products.Five.browser.pagetemplatefile, line 126, in __call__
  Module Products.Five.browser.pagetemplatefile, line 61, in __call__
  Module zope.pagetemplate.pagetemplate, line 135, in pt_render
  Module Products.PageTemplates.engine, line 88, in __call__
  Module z3c.pt.pagetemplate, line 173, in render
  Module chameleon.zpt.template, line 306, in render
  Module chameleon.template, line 209, in render
  Module chameleon.template, line 187, in render
  Module 9d0f91d0db1e48ba362ac742390c67e9, line 383, in render
  Module 74b7afc00771caaec9e36f1d4269a07c, line 376, in render_master
  Module 9d0f91d0db1e48ba362ac742390c67e9, line 373, in __fill_main
  Module 9d0f91d0db1e48ba362ac742390c67e9, line 114, in render_tiletypes
  Module Products.PageTemplates.expression, line 101, in __call__
  Module plone.memoize.view, line 48, in memogetter
  Module redturtle.tiles.management.browser.traversal, line 44, in tileTypes
AttributeError: 'SimpleViewClass from /home/yurj/old_home/progetti/' object has no attribute 'tileSortKey'

 - Expression: "view/tileTypes"
 - Filename:   ... agement/browser/overrides/plone.app.tiles.browser.add.pt
 - Location:   (line 19: col 34)
 - Source:     ... a tal:repeat="tiletype view/tileTypes" class="list-group-ite ...
                                          ^^^^^^^^^^^^^^
 - Expression: "context/global_statusmessage/macros/portal_message"
 - Filename:   ... .tiles-3.1.2-py2.7.egg/plone/app/tiles/browser/layout.pt
 - Location:   (line 28: col 38)
 - Source:     ... -macro="context/global_statusmessage/macros/portal_message">
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Expression: "context/@@tile-form-layout/macros/master"
 - Filename:   ... agement/browser/overrides/plone.app.tiles.browser.add.pt
 - Location:   (line 7: col 24)
 - Source:     ... k use-macro="context/@@tile-form-layout/macros/master">
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 - Arguments:  repeat: {...} (0)
               template: <ViewPageTemplateFile - at 0x7ff525296c90>
               views: <ViewMapper - at 0x7ff5256b1450>
               modules: <_SecureModuleImporter - at 0x7ff5369ea510>
               args: <tuple - at 0x7ff53e6ae050>
               here: <ImplicitAcquisitionWrapper homepage at 0x7ff52d0d72d0>
               wrapped_repeat: <SafeMapping - at 0x7ff525eca878>
               user: <ImplicitAcquisitionWrapper - at 0x7ff52d0ab550>
               nothing: <NoneType - at 0x55696ffaf4d0>
               root: <ImplicitAcquisitionWrapper  at 0x7ff52cfe3c30>
               container: <ImplicitAcquisitionWrapper homepage at 0x7ff52d0d72d0>
               request: <WSGIRequest - at 0x7ff525274ed0>
               traverse_subpath: <list - at 0x7ff5253197a0>
               default: <object - at 0x7ff53e5c2770>
               context: <ImplicitAcquisitionWrapper homepage at 0x7ff52d0d72d0>
               view: <SimpleViewClass from /home/yurj/old_home/progetti/plone/plone5/plone5/eggs/plone.app.tiles-3.1.2-py2.7.egg/plone/app/tiles/browser/add.pt add-tile at 0x7ff5256c7190>
               translate: <function translate at 0x7ff525294140>
               macroname: master
               options: {...} (0)
               loop: {...} (0)
               target_language: <NoneType - at 0x55696ffaf4d0>

**Comment by cekk** [comment]
E' un problema di redturtle.tilesmanagement.
C'è già un branch [python3](https://github.com/RedTurtle/redturtle.tiles.management/tree/python3) ma non è ancora stato rilasciato.

Dovresti provare ad abilitarlo in sviluppo su quel branch.

**Comment by yurj** [comment]
Grazie!
