### ISSUE TITLE
Bottone di chiusura mobile-menu sempre visibile

### ISSUE THREAD

**Issue by keul** [italia/design.plone.theme#88]
![Schermata 2020-03-09 alle 14 29 35](https://user-images.githubusercontent.com/284924/76226166-c52f3380-621d-11ea-88cb-5580ad19956b.png)

Partendo dal branch `python3_compatibility` vedo sempre visibile una **X** di chiusura di "qualcosa", dal markup parrebbe il mobile menù

```
<div id="mobile-menu" class="globalnavWrapper">
                <div class="menu-header">
                    <a href="javascript:void(0)" class="closebtn">
                        <svg class="svg-inline--fa fa-times fa-w-11" aria-hidden="true" data-prefix="fa" data-icon="times" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 352 512" data-fa-i2svg=""><path fill="currentColor" d="M242.72 256l100.07-100.07c12.28-12.28 12.28-32.19 0-44.48l-22.24-22.24c-12.28-12.28-32.19-12.28-44.48 0L176 189.28 75.93 89.21c-12.28-12.28-32.19-12.28-44.48 0L9.21 111.45c-12.28 12.28-12.28 32.19 0 44.48L109.28 256 9.21 356.07c-12.28 12.28-12.28 32.19 0 44.48l22.24 22.24c12.28 12.28 32.2 12.28 44.48 0L176 322.72l100.07 100.07c12.28 12.28 32.2 12.28 44.48 0l22.24-22.24c12.28-12.28 12.28-32.19 0-44.48L242.72 256z"></path></svg><!-- <span class="fa fa-times"></span> -->
                    </a>
                </div>
            </div>
```

Non trovo traccia di questo nel codice del tema, forse è qualcosa di nuovo della 5.2 nel core Plone

**Comment by pnicolli** [comment]
A memoria, mi pare di sì. In Plone 5.2 è stato rivisto il menù, nel momento in cui è stato reso dropdown multi-livello già nel core.

**Comment by yurj** [comment]
Salve,

 in questo caso si può correggere in qualche modo? O conviene usare questo tema con Plone 5.1?

**Comment by nzambello** [comment]
If you look at https://www.ge.camcom.gov.it/it (it uses this theme as a base) we actually have this:
```css
#mobile-menu {
    display: none;
}```

**Comment by yurj** [comment]
> If you look at https://www.ge.camcom.gov.it/it (it uses this theme as a base, running on py3/Plone5.2) we actually have this:
> 
> ```css
> #mobile-menu {
>     display: none;
> }
> ```

They use the hamburger menù there. For standard menù, this commit just remove the mobile menù.
